<?php

date_default_timezone_set('UTC');

// Work from the lib directory
chdir(dirname($argv[0]));

$LIB_DIR = getcwd(); // returns false on some Unix variants

if (!$LIB_DIR) {
  $LIB_DIR = $_SERVER['PWD'];
}

$APP_DIR = dirname($LIB_DIR);
$CONF_DIR = $APP_DIR . '/conf';
$CONFIG_FILE_INI = $CONF_DIR . '/config.ini';
$HTDOCS_DIR = $APP_DIR . '/htdocs';
$HTTPD_CONF = $CONF_DIR . '/httpd.conf';

if (!is_dir($CONF_DIR)) {
  mkdir($CONF_DIR, 0755, true);
}

// Check for non-interactive mode
foreach ($argv as $arg) {
  if ($arg === '--non-interactive') {
    define('NON_INTERACTIVE', true);
  }
}
if (!defined('NON_INTERACTIVE')) {
  define('NON_INTERACTIVE', false);
}

// Interactively prompt the user for config options and write config.ini
include_once 'configure.inc.php';

$CONFIG = parse_ini_file($CONFIG_FILE_INI);
$time = date('r');

// Write the httpd.conf file
file_put_contents($HTTPD_CONF, <<<OUT
## autogenerated at $time

Alias {$CONFIG['MOUNT_PATH']} $HTDOCS_DIR

<Location {$CONFIG['MOUNT_PATH']}>
  Order allow,deny
  Allow from all

  <LimitExcept POST GET>
    deny from all
  </LimitExcept>

  ExpiresActive on
  ExpiresDefault "access plus 30 minutes"
</Location>
OUT);
